server:
  port: 9010

database:
  url: "jdbc:postgresql://192.168.0.105:26257/user_data"
  username: "root"
  password: "root"
  driver: "org.postgresql.Driver"
  modelPackage: "org.data.model"

redis:
  url: "192.168.0.105"
  port: 6399

event-db:
  driver: "postgresql"
  host: "192.168.0.105"
  port: 5432
  user: "postgres"
  password: "password"
  database: "postgres"
  poolSize: 5
  maxIdleTime: 1000

